image: Visual Studio 2017
branches:
  only:
  - master
version: 3.0.{build}
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}.{build}'
  package_version: '{version}.{build}'
  assembly_version: '{version}.{build}'
  file_version: '{version}.{build}'
  informational_version: '{version}.{build}'
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./TheGodfather/TheGodfather.csproj --verbosity m
build_script:
  # output will be in ./TheGodfather/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./TheGodfather/TheGodfather.csproj
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  # restore packages for our unit tests
  #- cmd: dotnet restore ./TheGodfatherTests/TheGodfatherTests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  #- cmd: cd TheGodfatherTests
  #- cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off