image: Visual Studio 2017

branches:
  only:
  - master

version: 4.1.{build}

init:
  - cmd: git config --global core.autocrlf true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)
  assembly_version: $(appveyor_build_version)
  file_version: $(appveyor_build_version)
  informational_version: $(appveyor_build_version)

install:

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./TheGodfather/TheGodfather.csproj --verbosity m

build_script:
  - cmd: dotnet publish ./TheGodfather/TheGodfather.csproj /p:Version=%APPVEYOR_BUILD_VERSION%
  - cmd: 7z a TheGodfather.zip "%APPVEYOR_BUILD_FOLDER%\TheGodfather\bin\Release\netcoreapp2.1\publish\*"
  - cmd: 7z a TheGodfather.zip "%APPVEYOR_BUILD_FOLDER%\Scripts\*"
  - cmd: 7z a TheGodfatherResources.zip "%APPVEYOR_BUILD_FOLDER%\TheGodfather\Resources\*"

artifacts:
  - path: TheGodfather.zip
    name: TheGodfather Release Build
  - path: TheGodfatherResources.zip
    name: TheGodfather Release Resources

after_build:

clone_depth: 1

test_script:
  - cmd: dotnet restore ./TheGodfatherTests/TheGodfatherTests.csproj --verbosity m
  - cmd: cd TheGodfatherTests
  - cmd: dotnet test

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
on_finish:

deploy: off